baseURL = 'https://jurispuce.github.io/erakstnieks/'
languageCode = 'lv-LV'
defaultContentLanguage = 'lv'
title = 'eRakstnieks - Elektronisko dokumentu risinājumi'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Par mums"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Pakalpojumi"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "Infrastruktūra"
    url = "/infrastructure/"
    weight = 3
  [[menu.main]]
    name = "Apmācības"
    url = "/training/"
    weight = 4

[params]
  description = "Vadošais elektronisko dokumentu parakstīšanas un piegādes pakalpojumu sniedzējs"
  author = "eRakstnieks SIA"
  # Images will fallback to theme defaults if not present
  favicon = ""
  site_logo = ""
  background_color_class = "bg-navy"
  featured_image = ""
  recent_posts_number = 3
  mainSections = ["services", "training"]
  custom_css = ["css/custom.css"]
  
  # Social media links
  facebook = ""
  twitter = ""
  linkedin = ""

  [params.featured]
    hide_featured_image = false
    
  [params.colors]
    primary = "#0056b3"
    secondary = "#6c757d"