baseURL = 'https://jurispuce.github.io/erakstnieks/'
languageCode = 'lv-LV'
defaultContentLanguage = 'lv'
title = 'eRakstnieks - Elektronisko dokumentu risinājumi'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Sākums"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Par mums"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Pakalpojumi"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Infrastruktūra"
    url = "/infrastructure/"
    weight = 4
  [[menu.main]]
    name = "Apmācības"
    url = "/training/"
    weight = 5

[params]
  description = "Vadošais elektronisko dokumentu parakstīšanas un piegādes pakalpojumu sniedzējs"
  author = "eRakstnieks SIA"
  background_color_class = "bg-navy"
  featured_image = "/images/placeholder.svg"
  site_logo = ""  # Simple string instead of nested structure
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir"
  custom_css = ["css/custom.css"]
  
  [params.featured]
    hide_featured_image = false